incremental: true

domain: nwicomercialconstruction.com
twitter: "@DciPremier"
title: NWI Comercial Construction | Northwest Indiana | Construction Services
desc:  We provide commercial construction services, including design-build projects, new construction, and remodels. We strive to provide eco-friendly and energy-efficient construction solutions throughout Northwest Indiana at a competitive price
company_name: NWI Comercial Construction
phone_number: (877) 452-7405
email: Julius@nwicomercialconstruction.com
address: Northwest Indiana
address_link: https://goo.gl/maps/498pa3hM9qm
openingHours: "Mo,Tu,We,Th,Fr,Sat,Sun 00:00-24:00"
addressLocality: Crown Point
addressRegion: IN
postalCode: 46307
streetAddress: 8318 Morse Ct.
latitude: 39.879985
longitude: -86.267538
googleSiteVerification: E0SSgkJhxOBAGrRTzR5vC7q8sg0xpXj9rhcSxHbDEsw
social_platforms:
 - link: "#"
   icon: fab fa-facebook
 - link: "https://www.linkedin.com/in/julius-abraham-416374165/"
   icon: fab fa-linkedin-in
 - link: "https://www.yelp.com/biz/nwi-residential-construction-crown-point"
   icon: fab fa-yelp
 - link: "#"
   icon: fab fa-twitter